name: C/C++ CI

on:
  push:
    branches: [ flatcar-master ]
  pull_request:
    branches: [ flatcar-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt install -y libblkid-dev libext2fs-dev libmount-dev
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    #- name: make distcheck
    #  run: make distcheck
